# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-01 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALLBOOK',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='book uuid')),
                ('name', models.CharField(max_length=50, verbose_name='book name')),
                ('source', models.CharField(choices=[('d', 'dindian'), ('b', 'biqu')], max_length=5, verbose_name='get source')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='creat time')),
                ('uptime', models.DateTimeField(verbose_name='up data time')),
            ],
        ),
        migrations.CreateModel(
            name='BOOKTXT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.UUIDField(verbose_name='book cid')),
                ('number', models.IntegerField(verbose_name='book zhang')),
                ('zname', models.CharField(max_length=50, verbose_name='book zhang name')),
                ('surl', models.URLField(verbose_name='source link url')),
                ('ztext', models.TextField(verbose_name='page text')),
                ('creatime', models.DateTimeField(auto_now_add=True, verbose_name='creat time')),
                ('uptime', models.DateTimeField(verbose_name='up data time')),
            ],
        ),
        migrations.CreateModel(
            name='BOOKUPDATA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.UUIDField(verbose_name='book cid')),
                ('upinfo', models.CharField(max_length=200, verbose_name='updata info')),
                ('gotime', models.DateTimeField(auto_now_add=True, verbose_name='updata time')),
            ],
        ),
    ]
